name: ci
on:
  workflow_dispatch:

jobs:
  Arm64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: "mpv-android/mpv-android"
        ref: "master"
        fetch-depth: 0
      
    - name: set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: download-deps
      working-directory: ./buildscripts
      run: |
        ./download.sh
          
    - name: build-apk
      working-directory: ./buildscripts
      run:  |
        ./buildall.sh --clean
        ./buildall.sh --arch arm64 mpv
      
    - name: relocate apks
      run: |
        mkdir -p app/build/outputs/apk/release
        cp "./app/build/outputs/apk/default/release/app-default-universal-release-unsigned.apk"  app/build/outputs/apk/release/mpv-default-universal-release.apk
        cp "./app/build/outputs/apk/default/release/app-default-armeabi-v7a-release-unsigned.apk" app/build/outputs/apk/release/mpv-default-armeabi-v7a-release.apk
        cp "./app/build/outputs/apk/default/debug/app-default-universal-debug.apk" app/build/outputs/apk/release/mpv-default-universal-debug.apk       
        cp "./app/build/outputs/apk/default/debug/app-default-armeabi-v7a-debug.apk" app/build/outputs/apk/release/mpv-default-armeabi-v7a-debug.apk
      
    - name: Sign APK 
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGN_FILE_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}        

    - name: Get current time
      run: |
        echo "short_time=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
    
    - name: Release      
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: mpv-${{ env.short_time }}
        files: app/build/outputs/apk/release/mpv-*signed.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
