
name: build
on:
  workflow_dispatch:

jobs:
  Arm64:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v3
        with:
          repository: "mpv-android/mpv-android"
          ref: "master"
          fetch-depth: 0
      
      - name: set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: download-deps
        working-directory: ./buildscripts
        run: |
          ./download.sh
          
      - name: build-apk
        working-directory: ./buildscripts
        run:  |
          ./buildall.sh --clean
          ./buildall.sh --arch arm64 mpv
      
     - name: relocate apks
        run: |
          mkdir -p app/build/outputs/apk/release
          cp "./app/build/outputs/apk/default/release/app-default-universal-release-unsigned.apk"  app/build/outputs/apk/release/mpv-default.apk
          cp "./app/build/outputs/apk/api29/release/app-api29-universal-release-unsigned.apk" app/build/outputs/apk/release/mpv-api29.apk
          cp "./app/build/outputs/apk/api29/debug/app-api29-universal-debug.apk" app/build/outputs/apk/release/mpv-api29-debug.apk
          cp "./app/build/outputs/apk/default/debug/app-default-universal-debug.apk" app/build/outputs/apk/release/mpv-default-debug.apk
      - name: Sign APK
        uses: ilharp/sign-android-release@v1.0.2 # Or use @nightly
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0

      - name: Get current time
        run: |
          echo "short_time=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
    
      - name: Release      
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: mpv-${{ env.short_time }}
          files: app/build/outputs/apk/release/mpv-default-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
